version: '3.1'
services:
  worker:
    container_name: bw-backup-worker
    build: .
    restart: always
    volumes:
      - $HOST_DATA_DIR:/data
      - $HOST_BACKUP_DIR:/backups
      - $HOST_RCLONE_CONFIG:/root/.config/rclone/rclone.conf
    env_file:
      - .env